name: unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependences
      run: sudo apt update && sudo apt-get install -y g++-12 libgflags-dev libgtest-dev

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake test -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: bash
      env:
       CC:   gcc-12
       CXX:  g++-12

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} -j3
      shell: bash
      env:
       CC:   gcc-12
       CXX:  g++-12

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose

  build-on-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install dependences
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gflags
          mingw-w64-x86_64-gtest

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake test -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: build
      run: mingw32-make -j3

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose -E benchmark  # do not run benchmark due to Windows internal bugs
